tasks:
    - name: Start Xray
      init: |
        wget https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip
        unzip Xray-linux-64.zip
        chmod +x xray
      command: |
        ./xray -config config.json

  ports:
    - port: 8080
      onOpen: open-preview
